# This is a basic workflow to help you get started with Actions

name: armTemplateDeployment
on:
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name : Azure Login
        uses : Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group rg-githubactions with AZ CLI
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: 055a492d-25a8-4589-b838-79168f8c0b65
          region: West Europe
          template: ./arm-templates/resourcegroup.json
          deploymentName: rg-githubactions




